#!/bin/zsh -f
# Build CcsUsageMenuBar.app into macos/CcsUsageMenuBar/.build/ and install (optional).
# Usage: ./make-app.sh [--install]   (--install copies to /Applications and launches)

set -e
cd "$(dirname "$0")"

APP_NAME="CcsUsage"
APP_DIR=".build/${APP_NAME}.app"
CONTENTS="$APP_DIR/Contents"

swift build -c release

rm -rf "$APP_DIR"
mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"
cp Sources/CcsUsageMenuBar/Resources/AppIcon2.icns "$CONTENTS/Resources/AppIcon2.icns"

cp .build/release/CcsUsageMenuBar "$CONTENTS/MacOS/$APP_NAME"

cat > "$CONTENTS/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key><string>$APP_NAME</string>
    <key>CFBundleIdentifier</key><string>com.auf.ccs-usage-menubar</string>
    <key>CFBundleName</key><string>$APP_NAME</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>0.1.0</string>
    <key>LSUIElement</key><true/>
    <key>NSHighResolutionCapable</key><true/>
    <key>CFBundleIconFile</key><string>AppIcon2</string>
</dict>
</plist>
PLIST

# Stable signature so Keychain ACLs (claude-swap token access) survive rebuilds —
# ad-hoc signatures change every build and re-trigger the permission prompt.
codesign --force --sign "Apple Development" "$APP_DIR" 2>/dev/null \
  || echo "warn: no signing identity found; keychain will re-prompt"

# The LaunchAgent supervises the app: RunAtLoad starts it at login, KeepAlive restarts
# it after a crash, ThrottleInterval keeps a crash loop from spinning. A login item
# (SMAppService) does none of that, and two launch paths race into two icons.
LABEL="com.milad.ccs.usage-menubar"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
DOMAIN="gui/$(id -u)"

install_agent() {
  mkdir -p "$HOME/Library/LaunchAgents"
  cat > "$PLIST" <<EOP
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!-- Generated by macos/CcsUsageMenuBar/make-app.sh --install. Re-run it to change this. -->
<dict>
    <key>Label</key><string>$LABEL</string>
    <key>ProgramArguments</key>
    <array><string>/Applications/$APP_NAME.app/Contents/MacOS/$APP_NAME</string></array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key><string>$HOME/.local/bin:$HOME/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><true/>
    <key>ThrottleInterval</key><integer>15</integer>
    <key>ProcessType</key><string>Interactive</string>
    <key>LimitLoadToSessionType</key><string>Aqua</string>
    <key>StandardOutPath</key><string>$HOME/Library/Logs/$LABEL.log</string>
    <key>StandardErrorPath</key><string>$HOME/Library/Logs/$LABEL.log</string>
</dict>
</plist>
EOP
  launchctl bootout "$DOMAIN/$LABEL" 2>/dev/null || true
  launchctl bootstrap "$DOMAIN" "$PLIST"
}

if [[ "$1" == "--install" ]]; then
  launchctl bootout "$DOMAIN/$LABEL" 2>/dev/null || true
  pkill -f "CcsUsage.app/Contents/MacOS/CcsUsage" 2>/dev/null || true
  rm -rf "/Applications/$APP_NAME.app"
  cp -R "$APP_DIR" /Applications/
  install_agent
  echo "Installed /Applications/$APP_NAME.app; supervised by $LABEL (launchctl print $DOMAIN/$LABEL)"
else
  echo "Built $PWD/$APP_DIR — run with --install to install to /Applications and launch."
fi
