#!/bin/zsh -f
# Build CcsUsageMenuBar.app into macos/CcsUsageMenuBar/.build/ and install (optional).
# Usage: ./make-app.sh [--install]            copy to /Applications and launch
#        ./make-app.sh --fleet <ssh-host>...  build once, install here and on each host
#        ./make-app.sh --install-only         install an existing .build/CcsUsage.app (what --fleet runs remotely)

set -e
cd "$(dirname "$0")"

APP_NAME="CcsUsage"
APP_DIR=".build/${APP_NAME}.app"
CONTENTS="$APP_DIR/Contents"

if [[ "$1" != "--install-only" ]]; then

# The usage view is packages/usage-view, bundled for JavaScriptCore. The output is checked
# in so `swift test` runs without bun; this keeps it current with the TypeScript.
(cd ../.. && bun build packages/usage-view/jsc-entry.ts --target browser --format iife \
  --outfile macos/CcsUsageMenuBar/Sources/CcsUsageMenuBar/Resources/usage-view.js)

swift build -c release

rm -rf "$APP_DIR"
mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"
cp Sources/CcsUsageMenuBar/Resources/AppIcon2.icns "$CONTENTS/Resources/AppIcon2.icns"
# SwiftPM's Bundle.module looks for its resource bundle at the .app root, where a file
# would break the signature, so the script goes to Contents/Resources for Bundle.main.
cp Sources/CcsUsageMenuBar/Resources/usage-view.js "$CONTENTS/Resources/usage-view.js"

cp .build/release/CcsUsageMenuBar "$CONTENTS/MacOS/$APP_NAME"

# The build the hub's drift check compares against origin/master; BuildReport posts it at launch.
GIT_SHA=$(git -C ../.. rev-parse HEAD)

cat > "$CONTENTS/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key><string>$APP_NAME</string>
    <key>CFBundleIdentifier</key><string>com.auf.ccs-usage-menubar</string>
    <key>CFBundleName</key><string>$APP_NAME</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>0.1.0</string>
    <key>LSUIElement</key><true/>
    <key>NSHighResolutionCapable</key><true/>
    <key>CFBundleIconFile</key><string>AppIcon2</string>
    <key>CcsGitSHA</key><string>$GIT_SHA</string>
</dict>
</plist>
PLIST

# Stable signature so any Keychain ACL the app holds survives rebuilds; ad-hoc
# signatures change every build and re-trigger the permission prompt.
codesign --force --sign "Apple Development" "$APP_DIR" 2>/dev/null \
  || echo "warn: no signing identity found; keychain will re-prompt"
fi

# The LaunchAgent supervises the app: RunAtLoad starts it at login, KeepAlive restarts
# it after a crash, ThrottleInterval keeps a crash loop from spinning. A login item
# (SMAppService) does none of that, and two launch paths race into two icons.
LABEL="com.milad.ccs.usage-menubar"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
DOMAIN="gui/$(id -u)"

install_agent() {
  mkdir -p "$HOME/Library/LaunchAgents"
  cat > "$PLIST" <<EOP
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!-- Generated by macos/CcsUsageMenuBar/make-app.sh --install. Re-run it to change this. -->
<dict>
    <key>Label</key><string>$LABEL</string>
    <key>ProgramArguments</key>
    <array><string>/Applications/$APP_NAME.app/Contents/MacOS/$APP_NAME</string></array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key><string>$HOME/.local/bin:$HOME/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><true/>
    <key>ThrottleInterval</key><integer>15</integer>
    <key>ProcessType</key><string>Interactive</string>
    <key>LimitLoadToSessionType</key><string>Aqua</string>
    <key>StandardOutPath</key><string>$HOME/Library/Logs/$LABEL.log</string>
    <key>StandardErrorPath</key><string>$HOME/Library/Logs/$LABEL.log</string>
</dict>
</plist>
EOP
  launchctl bootout "$DOMAIN/$LABEL" 2>/dev/null || true
  launchctl bootstrap "$DOMAIN" "$PLIST"
}

if [[ "$1" == "--install" || "$1" == "--install-only" || "$1" == "--fleet" ]]; then
  launchctl bootout "$DOMAIN/$LABEL" 2>/dev/null || true
  pkill -f "CcsUsage.app/Contents/MacOS/CcsUsage" 2>/dev/null || true
  rm -rf "/Applications/$APP_NAME.app"
  cp -R "$APP_DIR" /Applications/
  install_agent
  echo "Installed /Applications/$APP_NAME.app; supervised by $LABEL (launchctl print $DOMAIN/$LABEL)"
  if [[ "$1" == "--fleet" ]]; then
    shift
    # The one signed build goes everywhere, so a host without Xcode never has to compile it.
    for host in "$@"; do
      rsync -a --delete make-app.sh "$APP_DIR" "$host:/tmp/ccs-menubar/" \
        && ssh "$host" 'mkdir -p /tmp/ccs-menubar/.build && rm -rf /tmp/ccs-menubar/.build/CcsUsage.app && mv /tmp/ccs-menubar/CcsUsage.app /tmp/ccs-menubar/.build/ && zsh -f /tmp/ccs-menubar/make-app.sh --install-only' \
        | sed "s/^/$host: /"
    done
  fi
else
  echo "Built $PWD/$APP_DIR — run with --install to install to /Applications and launch."
fi
