#!/usr/bin/env bash
# Stage a sidebar release and install (or reinstall) its LaunchAgent.
#
# Usage: install-sidebar-agent.sh [main|fork] [<commit-ish>]
#
# Two instances run side by side, each serving a different cmux application: `main` on 8787
# against the official cmux socket, `fork` on 8788 against the isolated `cmux CCS.app` socket.
# They differ only in port, socket, and identity ref, so they share one plist template rather
# than drifting as two hand-maintained files.
#
# A release is a `git archive` export of one commit into ~/.local/share/ccs/sidebar-releases/<sha>,
# never a worktree: worktrees are disposable and must not be load-bearing for a long-lived service.
# Staging and installing live in one script because doing them separately is how a plist ends up
# pointing at a SHA nobody exported.
set -euo pipefail

INSTANCE="${1:-main}"
COMMITISH="${2:-HEAD}"

case "$INSTANCE" in
  main) PORT=8787; SOCKET="${HOME}/.local/state/cmux/cmux.sock"; LABEL="com.milad.ccs.sidebar" ;;
  fork) PORT=8788; SOCKET="/tmp/cmux-staging-ccs.sock";          LABEL="com.milad.ccs.sidebar-fork" ;;
  *) echo "usage: $(basename "$0") [main|fork] [<commit-ish>]" >&2; exit 2 ;;
esac

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SHA="$(git -C "$REPO_ROOT" rev-parse --short "$COMMITISH")"
RELEASE="${HOME}/.local/share/ccs/sidebar-releases/${SHA}"
DEST="${HOME}/Library/LaunchAgents/${LABEL}.plist"
CCS_BIN="${RELEASE}/bin/ccs"

# Fail before installing rather than after, so a broken job never gets bootstrapped.
command -v bun >/dev/null || { echo "bun not found in PATH" >&2; exit 1; }

# Refuse to ship a commit that is not on the remote: a release is meant to be reproducible, and
# a SHA that exists only on this Mac cannot be re-staged anywhere else.
git -C "$REPO_ROOT" merge-base --is-ancestor "$SHA" origin/master 2>/dev/null \
  || { echo "$SHA is not an ancestor of origin/master — push it before releasing" >&2; exit 1; }

if [[ ! -d "$RELEASE" ]]; then
  echo "staging release $SHA"
  mkdir -p "$RELEASE"
  git -C "$REPO_ROOT" archive "$SHA" | tar -x -C "$RELEASE"
  ( cd "$RELEASE" && bun install --frozen-lockfile )
fi

[[ -x "$CCS_BIN" ]] || { echo "missing executable ccs at $CCS_BIN" >&2; exit 1; }
# The identity seam lives in ccs-launch; a release without it would install as an anonymous `bun`.
[[ -x "${RELEASE}/bin/ccs-launch" ]] || { echo "release $SHA predates bin/ccs-launch" >&2; exit 1; }

mkdir -p "${HOME}/Library/LaunchAgents" "${HOME}/Library/Logs"

# ProgramArguments names bin/ccs directly rather than invoking bun against it. bin/ccs is a
# zsh/TypeScript polyglot whose first act is to re-exec through ccs-launch, which applies the
# process identity; putting `bun` first makes Bun the process before that seam runs and the
# server shows up as an anonymous `bun`.
#
# PROCID_REF is set explicitly because a release is a `git archive` export with no .git, so the
# identity script cannot derive a ref on its own. Without it both instances report a bare
# `ccs:sidebar` and become indistinguishable in `ps` — the exact failure this naming prevents.
cat > "$DEST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!-- Generated by scripts/launchd/install-sidebar-agent.sh. Re-run that script to change it;
     hand-edits are lost on the next release. -->
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${CCS_BIN}</string>
        <string>sidebar</string>
        <string>serve</string>
        <string>--port</string>
        <string>${PORT}</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>CMUX_SOCKET_PATH</key>
        <string>${SOCKET}</string>
        <key>PROCID_REF</key>
        <string>${INSTANCE}</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>${HOME}/Library/Logs/${LABEL}.log</string>
    <key>StandardErrorPath</key>
    <string>${HOME}/Library/Logs/${LABEL}.log</string>
</dict>
</plist>
PLIST

plutil -lint "$DEST" >/dev/null

if launchctl print "gui/$(id -u)/${LABEL}" >/dev/null 2>&1; then
  launchctl bootout "gui/$(id -u)/${LABEL}"
fi
launchctl bootstrap "gui/$(id -u)" "$DEST"

# Prove it came back named and serving, rather than reporting success on a bootstrap that
# started a process which then died.
for _ in $(seq 1 40); do
  PID="$(launchctl print "gui/$(id -u)/${LABEL}" 2>/dev/null | sed -n 's/^[[:space:]]*pid = \([0-9]*\)$/\1/p')"
  [[ -n "${PID:-}" ]] && curl --fail --silent "http://127.0.0.1:${PORT}/" >/dev/null 2>&1 && break
  sleep 0.25
done

[[ -n "${PID:-}" ]] || { echo "agent did not report a pid — see ${HOME}/Library/Logs/${LABEL}.log" >&2; exit 1; }
ps -p "$PID" -o args= | grep -q "ccs:sidebar@${INSTANCE}" \
  || { echo "process is not carrying identity ccs:sidebar@${INSTANCE}" >&2; exit 1; }

echo "installed ${LABEL} — release ${SHA}, port ${PORT}, pid ${PID}"
ps -p "$PID" -o args=
