/**
 * Launcher environment specs — the compile step between `[[launcher]].env` in config.toml and
 * the `~/.ccs/bin/claude` shim that actually applies it.
 *
 * WHY A COMPILE STEP. The shim is plain bash on the hottest path on this machine: every
 * interactive `claude`, every resume, every managed birth passes through it. It cannot parse
 * TOML, and it must not shell out to `ccs` merely to learn its environment — that would put a
 * Bun start-up (and a total dependency on ccs being healthy) in front of paths that today have
 * neither, including `claude --version` and `claude --resume`. So `ccs launcher install`
 * MATERIALIZES each launcher's environment as a tiny directive file the shim reads with no
 * parser, no eval, and no subprocess.
 *
 * WHY DIRECTIVES INSTEAD OF A SOURCEABLE SCRIPT. A generated `.sh` that the shim `source`s
 * would be arbitrary code execution seeded by config. The directive format below is read
 * line-by-line and dispatched over a fixed three-verb vocabulary, so a malformed or hostile
 * spec can set a variable this file already validated and nothing else.
 *
 * The file format (one directive per line, `#` comments and blank lines ignored):
 *
 *   set     KEY=literal value
 *   setfile KEY=/absolute/path/to/a/secret
 *   clear   KEY
 */
import { type Result, err, ok } from "../result.ts";
import { expandHome } from "../paths.ts";

/** POSIX-portable environment variable names only; matches the cmux transport's own gate. */
const ENVIRONMENT_KEY_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;

/**
 * Marks a value as the CONTENTS OF A FILE rather than the value itself. The secret is then
 * named in config and read by the shim at exec time — it is never written into config.toml, never
 * copied into the materialized spec, and never sits at rest in a second place that has to be
 * rotated in step with the first. `~` is expanded at compile time so the shim resolves nothing.
 */
const FILE_VALUE_PREFIX = "@file:";

/** Escape hatch for a literal value that genuinely begins with `@file:`. */
const LITERAL_VALUE_PREFIX = "@literal:";

/** One resolved environment assignment, before it is rendered into the spec file. */
export type LauncherEnvValue =
  | { readonly kind: "literal"; readonly value: string }
  | { readonly kind: "file"; readonly path: string };

/**
 * Classify one configured `env` value. Deliberately total and non-throwing: the only failure a
 * caller can hit is an empty file path, which would otherwise render an unreadable directive.
 */
export function parseLauncherEnvValue(value: string): Result<LauncherEnvValue> {
  if (value.startsWith(LITERAL_VALUE_PREFIX)) {
    return ok({ kind: "literal", value: value.slice(LITERAL_VALUE_PREFIX.length) });
  }
  if (value.startsWith(FILE_VALUE_PREFIX)) {
    const raw = value.slice(FILE_VALUE_PREFIX.length).trim();
    if (raw.length === 0) return err(new Error(`"${FILE_VALUE_PREFIX}" needs a file path`));
    return ok({ kind: "file", path: expandHome(raw) });
  }
  return ok({ kind: "literal", value });
}

/** The launcher facts this module compiles. Structurally a subset of `Launcher`. */
export interface LauncherEnvSpecInput {
  readonly name: string;
  readonly env: Readonly<Record<string, string>>;
  readonly clears: readonly string[];
}

function validateKey(name: string, key: string): Result<void> {
  if (!ENVIRONMENT_KEY_PATTERN.test(key)) {
    return err(new Error(`launcher "${name}" has an invalid environment key: ${JSON.stringify(key)}`));
  }
  return ok(undefined);
}

/**
 * A directive is one line, so a value carrying a newline (or a NUL) would silently become a
 * second directive. Reject it at compile time rather than let the shim misread it.
 */
function validateSingleLine(name: string, key: string, value: string): Result<void> {
  if (/[\n\r\0]/.test(value)) {
    return err(new Error(`launcher "${name}" environment value for "${key}" must be a single line`));
  }
  return ok(undefined);
}

/**
 * Compile one launcher into its spec-file contents.
 *
 * `clears` is emitted BEFORE `set`/`setfile` so a launcher may legitimately clear a broad family
 * of inherited variables and then re-assert one of them; the shim applies directives in file
 * order, making that ordering the contract rather than an accident.
 */
export function compileLauncherEnvSpec(input: LauncherEnvSpecInput): Result<string> {
  const lines: string[] = [
    "# Generated by `ccs launcher install`. Edit [[launcher]].env in ~/.ccs/config.toml instead.",
    `# launcher: ${input.name}`,
  ];

  for (const key of input.clears) {
    const valid = validateKey(input.name, key);
    if (!valid.ok) return valid;
    lines.push(`clear ${key}`);
  }

  for (const [key, rawValue] of Object.entries(input.env)) {
    const valid = validateKey(input.name, key);
    if (!valid.ok) return valid;
    const parsed = parseLauncherEnvValue(rawValue);
    if (!parsed.ok) {
      return err(new Error(`launcher "${input.name}" environment value for "${key}": ${parsed.error.message}`));
    }
    const value = parsed.value.kind === "file" ? parsed.value.path : parsed.value.value;
    const singleLine = validateSingleLine(input.name, key, value);
    if (!singleLine.ok) return singleLine;
    lines.push(`${parsed.value.kind === "file" ? "setfile" : "set"} ${key}=${value}`);
  }

  return ok(`${lines.join("\n")}\n`);
}

/** Spec filename for a launcher. Names are constrained so this can never escape its directory. */
export function launcherEnvSpecFilename(name: string): Result<string> {
  if (!/^[A-Za-z0-9._-]+$/.test(name) || name === "." || name === "..") {
    return err(new Error(`launcher name is not usable as a filename: ${JSON.stringify(name)}`));
  }
  return ok(`${name}.env`);
}
