import {
  chmodSync,
  closeSync,
  existsSync,
  lstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  readdirSync,
  realpathSync,
  renameSync,
  statSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { runtimeRoot } from "../paths.ts";
import { err, ok, type Result } from "../result.ts";
import { loadConfig, type Config } from "../config.ts";
import { effectiveLaunchers, type Launcher } from "../resume/launchers.ts";
import { loadLauncherRegistry } from "./registry.ts";
import { loadLocationRegistry } from "../locations/registry.ts";
import { compileLauncherEnvSpec, launcherEnvSpecFilename } from "./environment.ts";
import {
  expectedBundledWrappers,
  isBundledWrapperBinary,
  wrapperManifestContents,
  WRAPPER_MANIFEST_FILE,
  type BundledWrapper,
} from "./wrappers.ts";

const START_MARKER = "# >>> CCS managed Claude launcher >>>";
const END_MARKER = "# <<< CCS managed Claude launcher <<<";

/** Filename holding the default launcher name the shim reads when CCS_FORCE_HARNESS is unset. */
const DEFAULT_LAUNCHER_FILE = "default";
let atomicWriteSequence = 0;

export interface ClaudeShimInstallation {
  readonly shimPath: string;
  readonly shellInitPath: string;
  readonly zshrcPath: string;
  readonly launcherEnvDir: string;
  /** Launcher names whose specs were materialized, in config order. */
  readonly launchers: readonly string[];
  /** Bundled launcher wrappers installed beside the PATH-precedent shim. */
  readonly wrappers: readonly string[];
  /** The launcher `claude` resolves to with no CCS_FORCE_HARNESS; null when undeclared. */
  readonly defaultLauncher: string | null;
}

export interface ClaudeShimInstallOptions {
  readonly sourcePath?: string;
  readonly wrapperSourceDir?: string;
  readonly root?: string;
  readonly zshrcPath?: string;
  /** Injected for tests; production reads ~/.ccs/config.toml. */
  readonly config?: Config;
}

function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

export function managedZshrcBlock(shellInitPath: string): string {
  return `${START_MARKER}\n[ -f ${shellSingleQuote(shellInitPath)} ] && source ${shellSingleQuote(shellInitPath)}\n${END_MARKER}`;
}

export function updateZshrc(content: string, shellInitPath: string): string {
  const block = managedZshrcBlock(shellInitPath);
  const start = content.indexOf(START_MARKER);
  const end = content.indexOf(END_MARKER);
  if (start !== -1 && end !== -1 && end >= start) {
    const after = end + END_MARKER.length;
    return `${content.slice(0, start)}${block}${content.slice(after)}`;
  }
  const separator = content.length === 0 || content.endsWith("\n") ? "" : "\n";
  return `${content}${separator}\n${block}\n`;
}

export function launcherShellInitContents(shimPath: string): string {
  return [
    "# Generated by `ccs launcher install`.",
    "# The PATH-precedent pass captures causal parentage before cmux clears Claude's",
    "# inherited session identity; CMUX_CUSTOM_CLAUDE_PATH routes back for registration.",
    `export PATH=${shellSingleQuote(dirname(shimPath))}:\"$PATH\"`,
    `export CMUX_CUSTOM_CLAUDE_PATH=${shellSingleQuote(shimPath)}`,
    "",
  ].join("\n");
}

/**
 * The launcher `claude` resolves to when nothing forces one.
 *
 * DELIBERATELY the location registry's `default_harness` — the value that already decides which
 * launcher a CCS-managed BIRTH lands on. Interactive `claude` and managed births are the same
 * question ("which harness is the fleet on right now?"), and answering it twice is how they drift
 * apart. Reusing it makes moving the fleet exactly one edit, and makes the escape hatch back to
 * `claude-native` exactly one edit too. A second key here would have to be kept in sync with the
 * registry by hand, and the failure mode — interactive sessions on one harness, births on another
 * — is silent.
 *
 * Null (no registry configured, or none declared) means the shim applies no environment and the
 * raw binary launches on its own defaults, which is precisely today's behavior.
 */
export function resolveDefaultLauncher(
  config: Config,
  launchers: readonly Launcher[],
  fleetDeclared: boolean,
): Result<string | null> {
  // An undeclared fleet (neither the shared registry nor `[[launcher]]` entries) means `launchers`
  // is the hardcoded `claude` fallback. There is nothing to point a default at, and `launcher
  // install` must stay usable on such a host — the feature is invisible until a fleet exists.
  if (!fleetDeclared) return ok(null);
  const registryPath = config.routing.registry;
  if (!registryPath || !existsSync(registryPath)) return ok(null);
  const registry = loadLocationRegistry(registryPath);
  if (!registry.ok) return registry;
  const harness = registry.value.defaultHarness;
  if (!harness) return ok(null);
  if (!launchers.some((launcher) => launcher.name === harness)) {
    return err(new Error(
      `location registry default_harness "${harness}" has no launcher entry in the shared registry ` +
        `or config.toml; declared launchers: ${launchers.map((l) => l.name).join(", ")}`,
    ));
  }
  return ok(harness);
}

function atomicWriteFile(path: string, contents: string | Uint8Array, mode: number): void {
  const temporary = `${path}.tmp-${process.pid}-${atomicWriteSequence++}`;
  try {
    writeFileSync(temporary, contents, { mode, flag: "wx" });
    chmodSync(temporary, mode);
    renameSync(temporary, path);
  } finally {
    rmSync(temporary, { force: true });
  }
}

function validateManagedDirectory(path: string): Result<void> {
  try {
    const stat = lstatSync(path);
    if (stat.isSymbolicLink() || !stat.isDirectory()) {
      return err(new Error(`managed launcher path is not a real directory: ${path}`));
    }
    return ok(undefined);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return ok(undefined);
    return err(error instanceof Error ? error : new Error(String(error)));
  }
}

function processIsAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    return (error as NodeJS.ErrnoException).code !== "ESRCH";
  }
}

function acquireInstallLock(root: string): Result<() => void> {
  const validRoot = validateManagedDirectory(root);
  if (!validRoot.ok) return validRoot;
  try {
    mkdirSync(root, { recursive: true, mode: 0o700 });
    const lockPath = join(root, "launcher-install.lock");
    const open = (): Result<number> => {
      try {
        return ok(openSync(lockPath, "wx", 0o600));
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "EEXIST") {
          return err(error instanceof Error ? error : new Error(String(error)));
        }
        let owner = Number.NaN;
        try {
          owner = Number.parseInt(readFileSync(lockPath, "utf8").trim(), 10);
        } catch {
          // An unreadable lock is not safe to steal.
        }
        if (!Number.isInteger(owner) || processIsAlive(owner)) {
          return err(new Error(`another launcher installation holds ${lockPath}`));
        }
        rmSync(lockPath, { force: true });
        try {
          return ok(openSync(lockPath, "wx", 0o600));
        } catch (retryError) {
          return err(retryError instanceof Error ? retryError : new Error(String(retryError)));
        }
      }
    };
    const descriptor = open();
    if (!descriptor.ok) return descriptor;
    try {
      writeFileSync(descriptor.value, `${process.pid}\n`);
    } catch (error) {
      closeSync(descriptor.value);
      rmSync(lockPath, { force: true });
      return err(error instanceof Error ? error : new Error(String(error)));
    }
    return ok(() => {
      try {
        closeSync(descriptor.value);
      } catch {
        // A dead-process lock is reclaimed on the next install.
      }
      try {
        rmSync(lockPath, { force: true });
      } catch {
        // A dead-process lock is reclaimed on the next install.
      }
    });
  } catch (error) {
    return err(error instanceof Error ? error : new Error(String(error)));
  }
}

interface UserFileSnapshot {
  readonly exists: boolean;
  readonly contents: string;
}

function readUserFile(path: string): Result<UserFileSnapshot> {
  try {
    const stat = lstatSync(path);
    if (!stat.isFile() && !stat.isSymbolicLink()) {
      return err(new Error(`user shell config is not a regular file or symlink: ${path}`));
    }
    return ok({ exists: true, contents: readFileSync(path, "utf8") });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      try {
        lstatSync(path);
      } catch (lstatError) {
        if ((lstatError as NodeJS.ErrnoException).code === "ENOENT") {
          return ok({ exists: false, contents: "" });
        }
      }
    }
    return err(error instanceof Error ? error : new Error(String(error)));
  }
}

function updateUserFile(path: string, before: UserFileSnapshot, contents: string): Result<void> {
  const current = readUserFile(path);
  if (!current.ok) return current;
  if (current.value.exists !== before.exists || current.value.contents !== before.contents) {
    return err(new Error(`${path} changed during launcher installation; refusing to overwrite it`));
  }
  try {
    if (!before.exists) {
      atomicWriteFile(path, contents, 0o644);
      return ok(undefined);
    }
    const entry = lstatSync(path);
    const target = entry.isSymbolicLink() ? realpathSync(path) : path;
    const mode = statSync(target).mode & 0o777;
    atomicWriteFile(target, contents, mode);
    return ok(undefined);
  } catch (error) {
    return err(error instanceof Error ? error : new Error(String(error)));
  }
}

interface WrapperInstallPlan {
  readonly wrappers: readonly BundledWrapper[];
  readonly removals: readonly string[];
  readonly manifestPath: string;
  readonly transitionManifestContents: string;
  readonly manifestContents: string;
}

function readWrapperManifest(path: string): Result<readonly string[]> {
  if (!existsSync(path)) return ok([]);
  try {
    const stat = lstatSync(path);
    if (stat.isSymbolicLink() || !stat.isFile()) {
      return err(new Error(`wrapper ownership manifest is not a regular file: ${path}`));
    }
    const names = readFileSync(path, "utf8").split(/\r?\n/).filter(Boolean);
    for (const name of names) {
      const valid = launcherEnvSpecFilename(name);
      if (!valid.ok) return valid;
      if (!isBundledWrapperBinary(name)) {
        return err(new Error(`wrapper ownership manifest contains an unknown binary: ${name}`));
      }
    }
    return ok(names);
  } catch (error) {
    return err(error instanceof Error ? error : new Error(String(error)));
  }
}

/** Validate every predictable wrapper failure before mutating the live runtime. */
function planBundledWrapperInstall(
  binDirectory: string,
  sourceDirectory: string,
  launchers: readonly Launcher[],
): Result<WrapperInstallPlan> {
  const wrappers = expectedBundledWrappers(sourceDirectory, binDirectory, launchers);
  if (!wrappers.ok) return wrappers;
  const manifestPath = join(binDirectory, WRAPPER_MANIFEST_FILE);
  const previous = readWrapperManifest(manifestPath);
  if (!previous.ok) return previous;
  const owned = new Set(previous.value);

  try {
    for (const wrapper of wrappers.value) {
      const destination = join(binDirectory, wrapper.binary);
      let stat: ReturnType<typeof lstatSync>;
      try {
        stat = lstatSync(destination);
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
        throw error;
      }
      if (!owned.has(wrapper.binary)) {
        return err(new Error(`refusing to overwrite unowned launcher wrapper: ${destination}`));
      }
      if (stat.isSymbolicLink() || !stat.isFile()) {
        return err(new Error(`managed launcher wrapper is not a regular file: ${destination}`));
      }
    }
  } catch (error) {
    return err(error instanceof Error ? error : new Error(String(error)));
  }

  const current = new Set(wrappers.value.map((wrapper) => wrapper.binary));
  const removals = previous.value.filter((name) => !current.has(name));
  try {
    for (const name of removals) {
      const path = join(binDirectory, name);
      let stat: ReturnType<typeof lstatSync>;
      try {
        stat = lstatSync(path);
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
        throw error;
      }
      if (!stat.isFile() && !stat.isSymbolicLink()) {
        return err(new Error(`stale managed launcher wrapper is not removable as a file: ${path}`));
      }
    }
  } catch (error) {
    return err(error instanceof Error ? error : new Error(String(error)));
  }

  const transitionNames = [...new Set([...previous.value, ...current])]
    .sort((left, right) => left.localeCompare(right));
  return ok({
    wrappers: wrappers.value,
    removals,
    manifestPath,
    transitionManifestContents: transitionNames.length > 0 ? `${transitionNames.join("\n")}\n` : "",
    manifestContents: wrapperManifestContents(wrappers.value),
  });
}

function materializeBundledWrappers(binDirectory: string, plan: WrapperInstallPlan): void {
  // Claim every old and new wrapper first. If the process stops mid-install, the next run can
  // safely repair or remove every path instead of treating a just-written wrapper as unowned.
  atomicWriteFile(plan.manifestPath, plan.transitionManifestContents, 0o600);
  for (const wrapper of plan.wrappers) {
    atomicWriteFile(join(binDirectory, wrapper.binary), wrapper.contents, 0o755);
  }
  for (const name of plan.removals) rmSync(join(binDirectory, name), { force: true });
  atomicWriteFile(plan.manifestPath, plan.manifestContents, 0o600);
}

interface LauncherEnvPlan {
  readonly files: readonly { readonly filename: string; readonly contents: string }[];
  readonly defaultContents: string | null;
}

/** Compile every spec before any installed artifact changes. */
function planLauncherEnv(
  launchers: readonly Launcher[],
  defaultLauncher: string | null,
): Result<LauncherEnvPlan> {
  const files: { filename: string; contents: string }[] = [];
  for (const launcher of launchers) {
    const filename = launcherEnvSpecFilename(launcher.name);
    if (!filename.ok) return filename;
    const spec = compileLauncherEnvSpec({
      name: launcher.name,
      env: launcher.env,
      clears: launcher.clears,
    });
    if (!spec.ok) return spec;
    files.push({ filename: filename.value, contents: spec.value });
  }
  return ok({ files, defaultContents: defaultLauncher === null ? null : `${defaultLauncher}\n` });
}

/** Publish every new environment file before any wrapper starts selecting it. */
function writeLauncherEnv(directory: string, plan: LauncherEnvPlan): ReadonlySet<string> {
  mkdirSync(directory, { recursive: true });
  chmodSync(directory, 0o700);

  const written = new Set<string>();
  for (const file of plan.files) {
    atomicWriteFile(join(directory, file.filename), file.contents, 0o600);
    written.add(file.filename);
  }

  if (plan.defaultContents !== null) {
    atomicWriteFile(join(directory, DEFAULT_LAUNCHER_FILE), plan.defaultContents, 0o600);
    written.add(DEFAULT_LAUNCHER_FILE);
  }
  return written;
}

/** Remove old selectors only after every wrapper points at an already-published new spec. */
function cleanupLauncherEnv(directory: string, written: ReadonlySet<string>): void {
  for (const entry of readdirSync(directory)) {
    if (!written.has(entry)) rmSync(join(directory, entry), { force: true, recursive: true });
  }
}

function installClaudeShimUnlocked(
  options: ClaudeShimInstallOptions,
  root: string,
): Result<ClaudeShimInstallation> {
  const sourcePath = options.sourcePath ?? resolve(import.meta.dir, "../../bin/ccs-claude-shim");
  const wrapperSourceDir = options.wrapperSourceDir ?? resolve(import.meta.dir, "../../bin/wrappers");
  const shimPath = join(root, "bin", "claude");
  const shellInitPath = join(root, "shell", "launcher.zsh");
  const launcherEnvDir = join(root, "launcher-env");
  const zshrcPath = options.zshrcPath ?? join(homedir(), ".zshrc");

  for (const directory of [dirname(shimPath), dirname(shellInitPath), launcherEnvDir]) {
    const valid = validateManagedDirectory(directory);
    if (!valid.ok) return valid;
  }

  const config = options.config ? ok(options.config) : loadConfig();
  if (!config.ok) return config;
  // The SHARED (vault-backed) fleet folded with this machine's overrides — the same list every
  // spawn path routes on, so the materialized specs can never describe a different fleet.
  const launchers = effectiveLaunchers(config.value);
  if (!launchers.ok) return launchers;
  const sharedRegistry = loadLauncherRegistry(config.value.routing.launchers);
  if (!sharedRegistry.ok) return sharedRegistry;
  const fleetDeclared =
    config.value.launcher.length > 0 || (sharedRegistry.value?.launcher.length ?? 0) > 0;
  const defaultLauncher = resolveDefaultLauncher(config.value, launchers.value, fleetDeclared);
  if (!defaultLauncher.ok) return defaultLauncher;
  const environmentPlan = planLauncherEnv(launchers.value, defaultLauncher.value);
  if (!environmentPlan.ok) return environmentPlan;
  const wrapperPlan = planBundledWrapperInstall(dirname(shimPath), wrapperSourceDir, launchers.value);
  if (!wrapperPlan.ok) return wrapperPlan;

  let shimSource: Uint8Array;
  try {
    shimSource = readFileSync(sourcePath);
  } catch (error) {
    return err(error instanceof Error ? error : new Error(String(error)));
  }

  const zshrc = readUserFile(zshrcPath);
  if (!zshrc.ok) return zshrc;
  const nextZshrc = updateZshrc(zshrc.value.contents, shellInitPath);
  const shellInitContents = launcherShellInitContents(shimPath);

  try {
    mkdirSync(dirname(shimPath), { recursive: true });
    mkdirSync(dirname(shellInitPath), { recursive: true });
    atomicWriteFile(shimPath, shimSource, 0o755);
    const writtenEnv = writeLauncherEnv(launcherEnvDir, environmentPlan.value);
    materializeBundledWrappers(dirname(shimPath), wrapperPlan.value);
    cleanupLauncherEnv(launcherEnvDir, writtenEnv);
    atomicWriteFile(shellInitPath, shellInitContents, 0o644);
    const updatedZshrc = updateUserFile(zshrcPath, zshrc.value, nextZshrc);
    if (!updatedZshrc.ok) return updatedZshrc;
    return ok({
      shimPath,
      shellInitPath,
      zshrcPath,
      launcherEnvDir,
      launchers: launchers.value.map((launcher) => launcher.name),
      wrappers: wrapperPlan.value.wrappers.map((wrapper) => wrapper.binary),
      defaultLauncher: defaultLauncher.value,
    });
  } catch (error) {
    return err(error instanceof Error ? error : new Error(String(error)));
  }
}

export function installClaudeShim(
  options: ClaudeShimInstallOptions = {},
): Result<ClaudeShimInstallation> {
  const root = options.root ?? runtimeRoot();
  const lock = acquireInstallLock(root);
  if (!lock.ok) return lock;
  try {
    return installClaudeShimUnlocked(options, root);
  } finally {
    lock.value();
  }
}
