import {
  chmodSync,
  copyFileSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { runtimeRoot } from "../paths.ts";
import { err, ok, type Result } from "../result.ts";

const START_MARKER = "# >>> CCS managed Claude launcher >>>";
const END_MARKER = "# <<< CCS managed Claude launcher <<<";

export interface ClaudeShimInstallation {
  readonly shimPath: string;
  readonly shellInitPath: string;
  readonly zshrcPath: string;
}

export interface ClaudeShimInstallOptions {
  readonly sourcePath?: string;
  readonly root?: string;
  readonly zshrcPath?: string;
}

function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function managedZshrcBlock(shellInitPath: string): string {
  return `${START_MARKER}\n[ -f ${shellSingleQuote(shellInitPath)} ] && source ${shellSingleQuote(shellInitPath)}\n${END_MARKER}`;
}

export function updateZshrc(content: string, shellInitPath: string): string {
  const block = managedZshrcBlock(shellInitPath);
  const start = content.indexOf(START_MARKER);
  const end = content.indexOf(END_MARKER);
  if (start !== -1 && end !== -1 && end >= start) {
    const after = end + END_MARKER.length;
    return `${content.slice(0, start)}${block}${content.slice(after)}`;
  }
  const separator = content.length === 0 || content.endsWith("\n") ? "" : "\n";
  return `${content}${separator}\n${block}\n`;
}

export function installClaudeShim(
  options: ClaudeShimInstallOptions = {},
): Result<ClaudeShimInstallation> {
  const root = options.root ?? runtimeRoot();
  const sourcePath = options.sourcePath ?? resolve(import.meta.dir, "../../bin/ccs-claude-shim");
  const shimPath = join(root, "bin", "claude");
  const shellInitPath = join(root, "shell", "launcher.zsh");
  const zshrcPath = options.zshrcPath ?? join(homedir(), ".zshrc");

  try {
    mkdirSync(dirname(shimPath), { recursive: true });
    mkdirSync(dirname(shellInitPath), { recursive: true });
    copyFileSync(sourcePath, shimPath);
    chmodSync(shimPath, 0o755);
    writeFileSync(
      shellInitPath,
      [
        "# Generated by `ccs launcher install`.",
        "# The PATH-precedent pass captures causal parentage before cmux clears Claude's",
        "# inherited session identity; CMUX_CUSTOM_CLAUDE_PATH routes back for registration.",
        `export PATH=${shellSingleQuote(dirname(shimPath))}:\"$PATH\"`,
        `export CMUX_CUSTOM_CLAUDE_PATH=${shellSingleQuote(shimPath)}`,
        "",
      ].join("\n"),
      { mode: 0o644 },
    );

    let zshrc = "";
    try {
      zshrc = readFileSync(zshrcPath, "utf8");
    } catch {
      // A missing zshrc is a valid fresh-machine state.
    }
    writeFileSync(zshrcPath, updateZshrc(zshrc, shellInitPath));
    return ok({ shimPath, shellInitPath, zshrcPath });
  } catch (error) {
    return err(error instanceof Error ? error : new Error(String(error)));
  }
}
