// Package data reads the existing CCS index and catalogue without reimplementing
// Claude Code transcript parsing. The SQLite files remain owned by ccs; this
// package opens them read-only and normalizes their rows for the TUI.
package data

import "time"

// ProviderCost is a cost rollup grouped by model vendor.
type ProviderCost struct {
	Claude float64
	GPT    float64
	Other  float64
}

// Add returns the component-wise sum of two provider rollups.
func (c ProviderCost) Add(other ProviderCost) ProviderCost {
	return ProviderCost{
		Claude: c.Claude + other.Claude,
		GPT:    c.GPT + other.GPT,
		Other:  c.Other + other.Other,
	}
}

// Total returns the complete provider spend.
func (c ProviderCost) Total() float64 {
	return c.Claude + c.GPT + c.Other
}

// LoadOptions controls which normally hidden session classes are included.
type LoadOptions struct {
	IncludeArchived  bool
	IncludeSubagents bool
	IncludeAuxiliary bool
}

// DefaultLoadOptions matches the browser's initial view.
func DefaultLoadOptions() LoadOptions {
	return LoadOptions{}
}

// Session is one normalized browser row backed by the CCS index and catalogue.
type Session struct {
	ID                string
	ResumeID          string
	Path              string
	Title             string
	TitleSource       string
	State             string
	Class             string
	SessionClass      string
	IdentityKey       string
	IdentityKind      string
	Role              string
	Cluster           string
	Stage             string
	StoredCategory    string
	EffectiveCategory string
	CategoryName      string
	CategoryCompact   string
	CategoryColor     string
	CategoryFinding   string
	CategorySource    string
	CategoryFrom      string
	PRNumber          int
	PRState           string
	Project           string
	ProjectRoot       string
	CWD               string
	Branch            string
	Skeleton          string
	FirstAt           time.Time
	LastAt            time.Time
	Messages          int
	Models            []string
	LastModel         string
	Model             string
	SelfCost          float64
	TotalCost         float64
	ProviderCost      ProviderCost
	Duration          string
	Subagents         int
	ParentID          string
	TaskSubjects      []string
	TasksDone         int
	TasksInProgress   int
	TasksTotal        int
	LiveWindowRef     string
	LiveWorkspaceRef  string
	IsLoop            bool
	IsSubagent        bool
	Enrichment        Enrichment
}

// Enrichment is CCS's cached structured read of a session: what it was, what is still open, and
// what to do with it. Generated by `ccs enrich` (catalogue v38) and stored on the session's
// catalogue row, so the TUI only reads it — it never generates one.
//
// This is deliberately distinct from the on-demand summary behind `s`, which is produced live,
// held in memory, and discarded on quit. Enrichment is durable and shared with every other CCS
// consumer.
type Enrichment struct {
	// Enrichment's own name for the session, derived from how it actually ended rather than from
	// its opening turns. Never overwrites a human-set custom title — see resolveDisplayTitle.
	Title string
	// State is where the session stands NOW, present tense, addressed to the reader. Catalogue v40
	// split the old single `Summary` into this plus History, because that field had to be both
	// "where this stands" and "how it got here" and was always written in the second order — so
	// the state ended up in the final clause of a paragraph you had to read to the end of.
	State string
	// History is how it got there, past tense. Rendered on demand, never by default: nothing
	// required in order to act belongs here.
	History string
	// Next is the single thing to do first on resuming. Exactly one action.
	Next string
	// Remaining is everything still open after Next, so scope is judgeable before committing.
	Remaining string
	// One of: continue, complete, archive, handoff. Empty when the session has never been enriched.
	Recommendation string
	// Reason is CONDITIONAL under v40: non-empty only for archive, handoff, or junk. On continue
	// and complete it restated the verdict in hedged prose, so it is now required to be empty and
	// its presence means the verdict is one a reader would otherwise distrust.
	Reason string
	Junk   bool
	// CWDJudged is false when no location registry existed when this was written, i.e. the cwd
	// question was never put to the model. Distinct from CWDCorrect=false, which is a judgement
	// that the directory is wrong — rendering a warning for "never judged" would put a defect
	// marker on a third of the store for a question nobody asked.
	CWDJudged    bool
	CWDCorrect   bool
	SuggestedLoc string
	SuggestedCWD string
	AtMessages   int
	At           time.Time
}

// Present reports whether this session has ever been enriched. Recommendation is the key because
// it is written in the same statement as everything else and is CHECK-constrained non-empty.
func (e Enrichment) Present() bool { return e.Recommendation != "" }

// StaleBy is how many messages a session has gained since its enrichment was written.
//
// This has to be surfaced, not hidden: a confidently worded summary describing a session as it was
// forty turns ago is worse than no summary at all, because the reader has no cue to distrust it.
func (e Enrichment) StaleBy(currentMessages int) int {
	if !e.Present() {
		return 0
	}
	if delta := currentMessages - e.AtMessages; delta > 0 {
		return delta
	}
	return 0
}

// Dash contains the aggregate values rendered in the dashboard header.
type Dash struct {
	Host       string
	Sessions   int
	Spend      float64
	Active     int
	Parked     int
	Loops      int
	LoopSpend  float64
	AgentSpend float64
	TopCost    float64
	TopTitle   string
}

// TreeNode is a causal-tree row with the same rollup semantics as ccs tree.
type TreeNode struct {
	SessionID string
	ID        string
	Title     string
	Role      string
	Depth     int
	SelfCost  float64
	TotalCost float64
	Providers ProviderCost
}

// Launcher is one resume route: a configured CCS launcher paired with a handoff
// target (inline in this terminal, or a new cmux workspace).
type Launcher struct {
	Name    string
	Backend string
	Env     map[string]string
	Target  string
	// Serves reports whether this launcher's serves globs cover the session's replay
	// target: its final model, or the whole history when that field is unavailable.
	// It is advisory: it picks the preselected route and nothing
	// else. Both wrappers are the same Claude Code harness over the same
	// Anthropic-format transcript, so choosing the other one is the operator's call.
	Serves bool
	// Eligible reports whether the route can run at all — the only real block, and
	// currently only ever false for cmux when cmux is not installed.
	Eligible bool
	Default  bool
	Reason   string
}

// CatalogueServiceStatus is the process state reported by ccs catalogue-service check.
type CatalogueServiceStatus struct {
	Running bool `json:"running"`
	PID     int  `json:"pid"`
}

// CatalogueSourceIndexStatus is the source/index freshness reported by the catalogue service.
type CatalogueSourceIndexStatus struct {
	State                string `json:"state"`
	SourceLatestMtimeMs  int64  `json:"sourceLatestMtimeMs"`
	IndexedLatestMtimeMs int64  `json:"indexedLatestMtimeMs"`
	LagMs                int64  `json:"lagMs"`
	StaleAfterMs         int64  `json:"staleAfterMs"`
	SourceFiles          int    `json:"sourceFiles"`
	IndexedSessions      int    `json:"indexedSessions"`
	OutOfSyncSessions    int    `json:"outOfSyncSessions"`
	Generation           int64  `json:"generation"`
	IndexedAt            string `json:"indexedAt"`
	RefreshedAt          string `json:"refreshedAt"`
	LastErrorAt          string `json:"lastErrorAt"`
	LastError            string `json:"lastError"`
}

// CatalogueRefreshStats is the existing index refresh count returned by ccs.
type CatalogueRefreshStats struct {
	Scanned int `json:"scanned"`
	Parsed  int `json:"parsed"`
	Skipped int `json:"skipped"`
	Removed int `json:"removed"`
}

// CatalogueStatus records the fail-open preflight result attached to a TUI snapshot.
type CatalogueStatus struct {
	Checked      bool
	Healthy      bool `json:"healthy"`
	ServiceKnown bool
	Service      CatalogueServiceStatus     `json:"service"`
	SourceIndex  CatalogueSourceIndexStatus `json:"sourceIndex"`
	Recovery     CatalogueRefreshStats
	Failure      string
}

// RecoveredRows returns the number of rows indexed or removed during recovery.
func (s CatalogueStatus) RecoveredRows() int {
	return s.Recovery.Parsed + s.Recovery.Removed
}

// Snapshot is the immutable real-data view used by one TUI run.
type Snapshot struct {
	Sessions      []Session
	Tree          []TreeNode
	Stats         Dash
	ByID          map[string]int
	LoadedAt      time.Time
	IndexPath     string
	CataloguePath string
	Catalogue     CatalogueStatus
	Warnings      []string
}

// SessionByID returns a session from the snapshot.
func (s Snapshot) SessionByID(id string) (Session, bool) {
	idx, ok := s.ByID[id]
	if !ok || idx < 0 || idx >= len(s.Sessions) {
		return Session{}, false
	}
	return s.Sessions[idx], true
}
