package ui

import (
	"os"

	"ccsspike/data"
	"ccsspike/transcript"
)

// Shot renders a named real-data view at the fixed design-spec size.
func Shot(name string, snapshot data.Snapshot) string {
	model := New(snapshot)
	model.w, model.h = 132, 40
	model.cursor = nthSessionRow(model.rows, 3)
	model.treeCursor = min(3, max(0, len(snapshot.Tree)-1))
	if session, ok := model.selectedSession(); ok {
		if document, err := transcript.Read(session.Path, 2000); err == nil {
			model.transcripts[session.ID] = document
			model.peekSession = session.ID
			model.peekScroll = max(0, len(document.Lines)-6)
		}
	}
	switch name {
	case "browser":
		model.view, model.preview = ViewGroups, true
	case "nopreview":
		model.view, model.preview = ViewGroups, false
	case "tree":
		model.view = ViewTree
	case "transcript":
		if session, ok := model.selectedSession(); ok {
			if document, loaded := model.transcripts[session.ID]; loaded {
				model.reader = &transcriptReader{sessionID: session.ID, title: session.Title, document: document, scroll: 1_000_000}
			}
		}
	case "route":
		model.view, model.overlay = ViewGroups, OverlayRoute
		if session, ok := model.selectedSession(); ok {
			routes, err := data.LoadRoutes(session.Models)
			model.routeSession = session.ID
			model.routeLoading = false
			model.routes = routes
			model.routeCursor = defaultRouteIndex(routes)
			if err != nil {
				model.routeError = err.Error()
			}
		}
	case "organize":
		if session, ok := model.selectedSession(); ok {
			model.confirmation = &confirmation{kind: confirmArchive, title: "Archive session?", items: []confirmationItem{{sessionID: session.ID, title: session.Title, detail: "ccs mark --archived", enabled: true}}}
		}
	case "ai":
		if session, ok := model.selectedSession(); ok {
			summary := os.Getenv("SHOT_AI_SUMMARY")
			if summary == "" {
				summary = "AI summary is generated on demand from the normalized transcript tail.\nNo metadata is written for summaries."
			}
			model.summaries[session.ID] = summary
			model.status = "summary generated by codex"
		}
	case "help":
		model.overlay = OverlayHelp
	}
	return model.View()
}

func nthSessionRow(rows []row, wanted int) int {
	seen := 0
	for i, candidate := range rows {
		if candidate.header {
			continue
		}
		if seen == wanted {
			return i
		}
		seen++
	}
	return firstSessionRow(rows)
}
