package ui

import (
	"os"
	"strings"

	"ccsspike/data"
	"ccsspike/skills"
	"ccsspike/transcript"
)

// Shot renders a named real-data view at the fixed design-spec size.
func Shot(name string, snapshot data.Snapshot) string {
	model := New(snapshot)
	model.w, model.h = 132, 40
	// Shots render real data, and the memory column is only meaningful against
	// live processes. Sample once here — the ticker that keeps it fresh only
	// runs under a real bubbletea program.
	if home, err := os.UserHomeDir(); err == nil {
		model.procStats = data.SampleProcStats(home)
	}
	model.cursor = nthSessionRow(model.rows, 3)
	model.treeCursor = min(3, max(0, len(snapshot.Tree)-1))
	loadShotTranscript(&model)
	switch name {
	case "browser":
		model.view, model.preview = ViewGroups, true
	case "peek":
		model.view, model.preview = ViewGroups, true
		selectShotSession(&model, func(session data.Session) bool {
			return strings.Contains(strings.ToLower(session.Title), "research best tui")
		})
		loadShotTranscript(&model)
	case "dossier":
		// Pick a session whose enrichment has something to show — a wrong working directory or an
		// open thread — since a clean one renders the least interesting version of this panel.
		model.view, model.preview = ViewGroups, true
		// Prefer a misplaced session: the cwd note is the one enrichment field that reports a
		// defect rather than describing the session, so it is the version of this panel most
		// worth having a proof of.
		selectShotSession(&model, func(session data.Session) bool {
			return session.Enrichment.Present() && !session.Enrichment.CWDCorrect
		})
		if session, ok := model.selectedSession(); !ok || !session.Enrichment.Present() {
			selectShotSession(&model, func(session data.Session) bool {
				return session.Enrichment.Present()
			})
		}
	case "nopreview":
		model.view, model.preview = ViewGroups, false
	case "tree":
		model.view = ViewTree
	case "transcript":
		selectShotSession(&model, func(session data.Session) bool {
			return session.ProviderCost.GPT > 0 && session.State == "active"
		})
		loadShotTranscript(&model)
		if session, ok := model.selectedSession(); ok {
			if document, err := transcript.ReadAll(session.Path); err == nil {
				model.cacheFullTranscript(session.ID, document)
				model.openTranscriptDocument(session, document)
				model.reader.scroll = max(0, len(model.reader.visual)-max(1, model.h-6))
			}
		}
	case "options":
		model.view, model.overlay = ViewGroups, OverlayViewOptions
	case "stage":
		model.view = ViewFlat
		model.rebuildRows()
		model.cursor = firstSessionRow(model.rows)
	case "cost":
		model.view = ViewFlat
		model.options.sort = sortCost
		model.rebuildRows()
		model.cursor = firstSessionRow(model.rows)
	case "route":
		model.view, model.overlay = ViewGroups, OverlayRoute
		if session, ok := model.selectedSession(); ok {
			routes, err := data.LoadRoutes(session.Models)
			model.routeSession = session.ID
			model.routeLoading = false
			model.routes = routes
			model.routeCursor = defaultRouteIndex(routes)
			if err != nil {
				model.routeError = err.Error()
			}
		}
	case "organize":
		if session, ok := model.selectedSession(); ok {
			model.confirmation = &confirmation{kind: confirmArchive, title: "Archive session?", items: []confirmationItem{{sessionID: session.ID, title: session.Title, detail: "ccs mark --archived", enabled: true}}}
		}
	case "ai":
		if session, ok := model.selectedSession(); ok {
			summary := os.Getenv("SHOT_AI_SUMMARY")
			if summary == "" {
				summary = "AI summary is generated on demand from the normalized transcript tail.\nNo metadata is written for summaries."
			}
			model.summaries[session.ID] = summary
			model.status = "summary generated by codex"
		}
	case "skills", "skill-reader":
		model.mode = ModeSkills
		if registry, err := skills.Load(); err == nil {
			model.skills = registry
			model.rebuildSkillRows()
			if name == "skill-reader" {
				model.openSkillReader()
			}
		} else {
			model.skillError = err.Error()
		}
	case "help":
		model.overlay = OverlayHelp
	}
	return model.View()
}

func nthSessionRow(rows []row, wanted int) int {
	seen := 0
	for i, candidate := range rows {
		if candidate.header {
			continue
		}
		if seen == wanted {
			return i
		}
		seen++
	}
	return firstSessionRow(rows)
}

func selectShotSession(model *Model, predicate func(data.Session) bool) {
	for index, candidate := range model.rows {
		if candidate.header || candidate.sIdx < 0 || candidate.sIdx >= len(model.snapshot.Sessions) {
			continue
		}
		if predicate(model.snapshot.Sessions[candidate.sIdx]) {
			model.cursor = index
			return
		}
	}
}

func loadShotTranscript(model *Model) {
	session, ok := model.selectedSession()
	if !ok {
		return
	}
	if _, loaded := model.transcripts[session.ID]; loaded {
		return
	}
	if document, err := transcript.ReadRecent(session.Path, 200, 512*1024); err == nil {
		model.cachePeekTranscript(session.ID, document)
		model.transcriptLoadedAt[session.ID] = model.snapshot.LoadedAt
		model.peekSession = session.ID
		model.peekScroll = max(0, len(document.Lines)-6)
	}
}
